version = "1.0"

[main]
name = "Armadietto configuration"

    [main.is_signup]
    name = "Signup configuration"

        [main.is_signup.signup]
        ask.en = "Allow signups?"
        ask.fr = "Accepter les inscriptions ?"
        type = "boolean"
        yes = "true"
        no = "false"
        bind = ":__FINALPATH__/server.js"
        help.en = "Would you like to allow visitors to register and create an account?"
        help.fr = "Souhaitez-vous autoriser les visiteurs à s'inscrire et créer un compte ?"
